// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SPA.Data;

namespace SPA.Migrations
{
    [DbContext(typeof(AppDBContent))]
    [Migration("20201114091544_ShopSerevice")]
    partial class ShopSerevice
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SPA.Data.Models.Category", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("categoryName");

                    b.Property<string>("description");

                    b.Property<string>("img");

                    b.HasKey("id");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("SPA.Data.Models.Service", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("categoryID");

                    b.Property<string>("img");

                    b.Property<bool>("isFavourite");

                    b.Property<string>("longdesc");

                    b.Property<string>("name");

                    b.Property<int>("price");

                    b.Property<string>("shortdesc");

                    b.HasKey("id");

                    b.HasIndex("categoryID");

                    b.ToTable("Service");
                });

            modelBuilder.Entity("SPA.Data.Models.ShopServiceItem", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ShopServiceId");

                    b.Property<int>("price");

                    b.Property<int?>("serviceid");

                    b.HasKey("id");

                    b.HasIndex("serviceid");

                    b.ToTable("ShopServiceItem");
                });

            modelBuilder.Entity("SPA.Data.Models.Service", b =>
                {
                    b.HasOne("SPA.Data.Models.Category", "Category")
                        .WithMany("Services")
                        .HasForeignKey("categoryID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SPA.Data.Models.ShopServiceItem", b =>
                {
                    b.HasOne("SPA.Data.Models.Service", "service")
                        .WithMany()
                        .HasForeignKey("serviceid");
                });
#pragma warning restore 612, 618
        }
    }
}
